### ISSUE TITLE
Unable to find the 1x5 connector 

### ISSUE THREAD

**Issue by Allmentux** [jjrh/PGA2311#1]
It seems that the 1x5 connector has a spacing of 2mm instead of the normal 2,54mm/100mils.
This particular part seems to be unable to locate! Even in metric europe.
Do you have an idea on where to get it?

Found it... JST b5b-ph-kl seems to be the code for it.

**Comment by jjrh** [comment]
Allmentux writes:

> It seems that the 1x5 connector has a spacing of 2mm instead of the normal
> 2,54mm.
> This particular part seems to be unable to locate! Even in metric europe.
> Do you have an idea on where to get it?

I believe that's a jst footprint I got it from
http://smisioto.no-ip.org/elettronica/kicad/kicad-en.htm

"JST PH series connector, B2B-PH-KL"

I believe I had used this connector for another board and got the
connectors from aliexpress.

Keep in mind for this particular board I have _not_ sent this board to be fabbed yet as other
things have kept me busy. If you do get it fabbed or make some
modifications let me know!
